### ISSUE TITLE
Release pyne-cli-1.0-SNAPSHOT-jar-with-dependencies.jar 

### ISSUE THREAD

**Issue by asarkar** [darius-sas/pyne#8]
Instead of building from source code, consider releasing the compiled `pyne-cli-1.0-SNAPSHOT-jar-with-dependencies.jar` so that users can download it from the repository releases page. This is the simplest approach to distributing binaries without having to publish to a Maven repository like Maven Central.

**Comment by darius-sas** [comment]
Hello @asarkar , for your convenience, I published a release on the releases page: [1.1.0-RELEASE](https://github.com/darius-sas/pyne/releases/tag/1.1.0-RELEASE) building the jars on my local machine.

However, I'd like to point out that Pyne is an unmaintained project and uses an outdated version of [Spoon](https://spoon.gforge.inria.fr/) (the library that parses Java code). Pyne was integrated into Arcan several years ago, which we will be releasing as open source this fall, therefore, I discourage you to use Pyne for any other purpose than education.

Best,
Darius

**Comment by darius-sas** [comment]
I'm closing this issue
