### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by asarkar** [darius-sas/pyne#9]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for pyne 1.1-SNAPSHOT:
[INFO] 
[INFO] pyne ............................................... SUCCESS [  0.737 s]
[INFO] pyne-api ........................................... FAILURE [  5.462 s]
[INFO] pyne-cli ........................................... SKIPPED
[INFO] pyne-demo .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.250 s
[INFO] Finished at: 2023-07-30T17:17:18-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pyne-api: Could not resolve dependencies for project edu.rug:pyne-api:jar:1.1-SNAPSHOT: The following artifacts could not be resolved: fr.inria.gforge.spoon:spoon-core:jar:8.4.0-SNAPSHOT (absent): Could not find artifact fr.inria.gforge.spoon:spoon-core:jar:8.4.0-SNAPSHOT -> [Help 1]
```

This is because there's no `spoon-core:8.4.0-SNAPSHOT` dependency present in Maven Central. Changing that `spoon-core:8.4.0` to doesn't help, because then a unit test fails.

```
testFindSourceDirs  Time elapsed: 0.04 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at edu.rug.pyne.structure.ParserTest.testFindSourceDirs(ParserTest.java:19)
```

**Comment by darius-sas** [comment]
Hello @asarkar , thank you for reporting the build issue. I pushed a hot fix and everything should work as expected now. Let me know so I can close this issue.

**Comment by asarkar** [comment]
@darius-sas Thanks for the quick turnaround. However, given that these issues would have been blatantly obvious to anyone running a build, and still went undetected, I’d like to ask about the maintenance and testing plan for this repository. If this is an abandoned and unplanned project, then understandably as a user, I’d not want to spend any time with it.

**Comment by asarkar** [comment]
> maintenance and testing plan for this repository

I think my question was answered in [this comment](https://github.com/darius-sas/pyne/issues/8#issuecomment-1657815483), closing this ticket.  

> However, I'd like to point out that Pyne is an unmaintained project and uses an outdated version of [Spoon](https://spoon.gforge.inria.fr/) (the library that parses Java code). Pyne was integrated into Arcan several years ago, which we will be releasing as open source this fall, therefore, I discourage you to use Pyne for any other purpose than education.
